### ISSUE TITLE
Isaacs Gift

### ISSUE THREAD

**Issue by MajencioYT** [Xaiter/Binding-of-Isaac#2]

**Comment by Color-Printer** [comment]
Your original issue description is still visible under "edited", for the record. Anyway, this code was retrieved from a flash decompiler, is almost definitely obfuscated to some degree, and would likely only function properly when plugged back into the same flash project it was attached to. That project is, as far as I am aware, impossible to retrieve from the game in a condition whole enough to actually work with.
